input {
  tcp {
    port => 5000
    codec => json_lines
  }
}

filter {
  if [logger_name] {
    mutate {
      add_tag => ["shopping-backend"]
    }
  }
  if [status] >= 500 {
    mutate {
      add_tag => ["error"]
    }
  }
}

output {
  elasticsearch {
    hosts => ["${ES_HOSTS:-elasticsearch:9200}"]
    index => "shopping-logs-%{+YYYY.MM.dd}"
    user => "${ES_USER:-}"
    password => "${ES_PWD:-}"
  }
  stdout { codec => rubydebug }
}
